In [140]:
# from load_data import import_data
import pandas as pd
# First we sum the number of encounters and loiterings for each carrier.
# Then make a classification: if there are more encounters than loiterings, the carrier is not suspicious, if there is more loitering, the carrier is suspicious. (Don't hard-code the cutoff. We may want to do 66% loitering and 33% encounters in the future instead of 50-50)
# For every carrier in the carriers table, label a value 1 (suspicious) or 0 (not suspicious).


def import_data():
    path = 'gfw_data-v2.xlsx'
    xls = pd.ExcelFile(path)
    dfList = []
    for sheet in ['carriers', 'encounter', 'loitering', 'encounter-v2', 'loitering-v2']:
        dfList.append(pd.read_excel(path, sheet_name=sheet))
    return dfList

In [141]:
carriers, encounter, loitering, encounter2, loitering2 = import_data()

In [188]:
# def classify(carriers, encounter, loitering, cutoff = 0.5):
#     '''
#     Input: Global Fishing Watch data
#     Output: Adds column to each reefer indicating whether they are suspicious of IUU or not
#     '''

#     # count the num of encounter/loitering for each carrier
#     num_encounter = []
#     num_loitering = []
#     for i in carriers.id:
#         num_encounter.append(encounter[encounter['vessel1_id']==i].shape[0])
#         num_loitering.append(loitering[loitering['vessel_id']==i].shape[0])

#     # append the num info into new column in carrier table
#     carrier = carriers.assign(encounter = num_encounter, loitering = num_loitering)
#     # if cutoff*encounter >= (1-cutoff)*loitering then we set label = 0 as unsuspicious
#     # if cutoff*encounter < (1-cutoff)*loitering then we set label = 1 as suspicious
#     carrier['label'] = ((cutoff*carrier['encounter'] - (1-cutoff)*carrier['loitering']) < 0).astype(int)
#     return carrier

# def change_cutoff(data, cutoff = 0.5):
#     data['label'] = ((cutoff*data['encounter'] - (1-cutoff)*data['loitering']) < 0).astype(int)
#     return data

In [189]:
# classified_data = classify(carriers, encounter, loitering, 0.66)

In [190]:
# classified_data.head()

In [191]:
# classified_data['label'].sum()

In [192]:
# classified_data['label'].count()

In [193]:
# a = change_cutoff(classified_data, 0.99)

In [194]:
# a['label'].sum()

In [195]:
# carriers

In [ ]:
# num_encounter2 = []
# num_loitering2 = []
# for i in carriers.id:
# #     num_encounter2.append(encounter2[encounter2['vessel.id']==i].shape[0] + encounter2[encounter2['encounter.encountered_vessel.id']==i].shape[0])
#     num_loitering2.append(loitering2[loitering2['vessel.id']==i].shape[0])

# # append the num info into new column in carrier table
# carrier = carriers.assign(encounter2 = num_encounter2, loitering2 = num_loitering2)

In [ ]:
# carrier

In [ ]:
# loitering2

# Encounter Merging

In [143]:
encounter.columns

Index(['event_id', 'event_type', 'event_start', 'event_end', 'event_lat',
       'event_lon', 'mpa', 'eez', 'rfmo', 'fao', 'major_fao', 'eez12nm',
       'boundingBox', 'startDistanceFromShoreKm', 'endDistanceFromShoreKm',
       'startDistanceFromPortKm', 'endDistanceFromPortKm', 'vessel1_id',
       'vessel1_flag', 'vessel1_name', 'vessel1_type', 'vessel1_ssvid',
       'vessel2_id', 'vessel2_flag', 'vessel2_name', 'vessel2_type',
       'vessel2_ssvid', 'medianDistanceKilometers', 'medianSpeedKnots',
       'encounter_type'],
      dtype='object')

In [144]:
encounter2.columns

Index(['id', 'type', 'start', 'end', 'lat', 'lon', 'vessel.id', 'vessel.type',
       'vessel.mmsi', 'vessel.name', 'vessel.flag',
       'vessel.origin_port.country', 'vessel.origin_port.name',
       'vessel.destination_port.country', 'vessel.destination_port.name',
       'vessel.authorizations.authorized', 'vessel.authorizations.unknown',
       'median_speed_knots', 'elevation_m', 'distance_from_shore_m',
       'distance_from_port_m', 'regions.rfmo', 'encounter.median_distance_km',
       'encounter.authorization_status', 'encounter.encountered_vessel.id',
       'encounter.encountered_vessel.type',
       'encounter.encountered_vessel.mmsi',
       'encounter.encountered_vessel.name',
       'encounter.encountered_vessel.flag',
       'encounter.encountered_vessel.origin_port.country',
       'encounter.encountered_vessel.origin_port.name',
       'encounter.encountered_vessel.destination_port.country',
       'encounter.encountered_vessel.destination_port.name',
       'encounter.encountered_vessel.authorizations.authorized',
       'encounter.encountered_vessel.authorizations.unknown',
       'loitering.total_distance_km', 'loitering.loitering_hours', 'port.lat',
       'port.lon', 'port.country', 'port.name'],
      dtype='object')

In [145]:
encounter.columns = ['id', 'type', 'start', 'end', 'lat', 'lon','mpa', 'eez', 'regions.rfmo','fao', 'major_fao', 'eez12nm',
       'boundingBox', 'startDistanceFromShoreKm', 'endDistanceFromShoreKm',
       'startDistanceFromPortKm', 'endDistanceFromPortKm','vessel.id','vessel.flag','vessel.name','vessel.type','vessel.mmsi',
                  'encounter.encountered_vessel.id', 'encounter.encountered_vessel.flag', 'encounter.encountered_vessel.name',
                    'encounter.encountered_vessel.type','encounter.encountered_vessel.mmsi','medianDistanceKilometers', 'medianSpeedKnots',
       'encounter_type']

In [185]:
# ((encounter['start'].isin(encounter2['start'])) & (encounter['vessel.id'].isin(encounter2['vessel.id'])) & (encounter['encounter.encountered_vessel.id'].isin(encounter2['encounter.encountered_vessel.id']))).sum()

In [186]:
# (encounter['start'].isin(encounter2['start'])).sum()

In [150]:
(encounter['encounter.encountered_vessel.id'].isin(encounter2['encounter.encountered_vessel.id'])).sum()
(encounter['vessel.id'].isin(encounter2['encounter.encountered_vessel.id'])).sum()

dfdf = encounter[~((encounter['start'].isin(encounter2['start'])) & (encounter['vessel.id'].isin(encounter2['vessel.id'])) & (encounter['encounter.encountered_vessel.id'].isin(encounter2['encounter.encountered_vessel.id'])))]
dfdf = dfdf[~((dfdf['start'].isin(encounter2['start'])) & (dfdf['vessel.id'].isin(encounter2['encounter.encountered_vessel.id'])) & (dfdf['vessel.id'].isin(encounter2['encounter.encountered_vessel.id'])))]
dfdf

,id,type,start,end,lat,lon,mpa,eez,regions.rfmo,fao,...,vessel.type,vessel.mmsi,encounter.encountered_vessel.id,encounter.encountered_vessel.flag,encounter.encountered_vessel.name,encounter.encountered_vessel.type,encounter.encountered_vessel.mmsi,medianDistanceKilometers,medianSpeedKnots,encounter_type
2,bbc225900674c6a9c9d27fcfdb5600d9.1,encounter,2022-09-20 07:00:00,2022-09-20 23:50:00,62.9143,179.4136,NaN,5690,"IWC, PICES, ACAP",61,...,fishing,273240400,f7ebe6fa3-3640-5c7f-17c2-83423449bb1e,RUS,VITALIY SHMYKOV,carrier,273356290,0.049,0.015,fishing-carrier
3,bbc225900674c6a9c9d27fcfdb5600d9.2,encounter,2022-09-20 07:00:00,2022-09-20 23:50:00,62.9143,179.4136,NaN,5690,"PICES, ACAP, IWC",61,...,carrier,273356290,5ddb64d7e-ec33-e20d-7265-c717e3c59313,RUS,AHTIAR,fishing,273240400,0.049,0.015,carrier-fishing
4,30b519732007d7631f6f5fcc84049eee.2,encounter,2022-09-20 15:10:00,2022-09-20 20:30:00,48.7694,140.6118,NaN,5690,"IWC, ACAP, WCPFC, PICES",61,...,fishing,273433540,489bfeb6d-d541-4161-1236-a1d70a89f03d,RUS,DRUZHBA,carrier,273895510,0.022,0.691,fishing-carrier
5,30b519732007d7631f6f5fcc84049eee.1,encounter,2022-09-20 15:10:00,2022-09-20 20:30:00,48.7694,140.6118,NaN,5690,"WCPFC, ACAP, IWC, PICES",61,...,carrier,273895510,9b97aea07-748b-3980-155a-16708547d87b,RUS,SAPFIR-1,fishing,273433540,0.022,0.691,carrier-fishing
6,62c26fb35ff2e311e3de947a1816fa9d.1,encounter,2022-09-18 16:10:00,2022-09-20 20:10:00,62.2185,177.3961,NaN,5690,"PICES, IWC, ACAP",61,...,fishing,273896300,bb4deba8f-fa0b-a431-09fa-9b8486e05900,RUS,VOLKHOV,carrier,273432430,0.043,1.367,fishing-carrier
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114714,505bc1c356bc9d89430f09a2b7eeef7e.1,encounter,2013-05-16 03:30:00,2013-05-16 23:50:00,60.2419,-144.9064,306882,8463,"ACAP, IWC, PICES, IPHC",67,...,carrier,5004,bf4c2be79-9fe2-8ec3-f483-eef1943e21dc,USA,CHELSEA,fishing,369519000,0.164,0.002,carrier-fishing
115220,101e1c04cc21792c3ed54bf03a5e72b8.1,encounter,2013-01-31 21:10:00,2013-01-31 23:40:00,-6.4740,153.8343,NaN,8324,"SPC, WCPFC, ACAP, IWC, FFA",71,...,fishing,444042912,fcafb1c35-56cf-c3fc-f26a-10a06da06efc,VUT,OCEANUS,carrier,576507000,0.292,1.138,fishing-carrier
115221,101e1c04cc21792c3ed54bf03a5e72b8.2,encounter,2013-01-31 21:10:00,2013-01-31 23:40:00,-6.4740,153.8343,NaN,8324,"ACAP, IWC, WCPFC, FFA, SPC",71,...,carrier,576507000,8a709d9be-ede1-cb17-8532-23c9823d1480,NaN,ELSPETH,fishing,444042912,0.292,1.138,carrier-fishing
116296,336f5af6ae0e7291d9d719e9c92ffadf.1,encounter,2012-02-15 01:30:00,2012-02-15 06:10:00,-12.2030,61.8748,NaN,NaN,"IOTC, IWC, SIOFA, ACAP","51, 51.7",...,carrier,352373000,a7256d289-9347-9f3e-1c8e-1ce4d9fd8fbc,NaN,HSIANG FA 26,fishing,424426611,0.046,0.563,carrier-fishing
116297,336f5af6ae0e7291d9d719e9c92ffadf.2,encounter,2012-02-15 01:30:00,2012-02-15 06:10:00,-12.2030,61.8748,NaN,NaN,"ACAP, SIOFA, IWC, IOTC","51.7, 51",...,fishing,424426611,a718ea650-087f-72a7-3c2b-e887b584a791,PAN,HARIMA 2,carrier,352373000,0.046,0.563,fishing-carrier

In [187]:
# encounter.count()

In [151]:
frames = [encounter2,dfdf]

result = pd.concat(frames)

In [ ]:
compression_opts2 = dict(method='zip',
                        archive_name='new_encounter.csv')  
result.to_csv('new_encounter.zip', index=False,
          compression=compression_opts2)

# Loitering Merging

In [179]:
loitering.columns

Index(['event_id', 'event_type', 'event_start', 'event_end', 'event_lat',
       'event_lon', 'mpa', 'eez', 'rfmo', 'fao', 'major_fao', 'eez12nm',
       'boundingBox', 'startDistanceFromShoreKm', 'endDistanceFromShoreKm',
       'startDistanceFromPortKm', 'endDistanceFromPortKm', 'vessel_id',
       'vessel_name', 'vessel_type', 'vessel_ssvid', 'totalTimeHours',
       'totalDistanceKm', 'averageSpeedKnots', 'averageDistanceFromShoreKm'],
      dtype='object')

In [180]:
loitering2.columns

Index(['id', 'type', 'start', 'end', 'lat', 'lon', 'vessel.id', 'vessel.type',
       'vessel.mmsi', 'vessel.name', 'vessel.flag',
       'vessel.origin_port.country', 'vessel.origin_port.name',
       'vessel.destination_port.country', 'vessel.destination_port.name',
       'vessel.authorizations.authorized', 'vessel.authorizations.unknown',
       'median_speed_knots', 'elevation_m', 'distance_from_shore_m',
       'distance_from_port_m', 'regions.rfmo', 'encounter.median_distance_km',
       'encounter.authorization_status', 'encounter.encountered_vessel.id',
       'encounter.encountered_vessel.type',
       'encounter.encountered_vessel.mmsi',
       'encounter.encountered_vessel.name',
       'encounter.encountered_vessel.flag',
       'encounter.encountered_vessel.origin_port.country',
       'encounter.encountered_vessel.origin_port.name',
       'encounter.encountered_vessel.destination_port.country',
       'encounter.encountered_vessel.destination_port.name',
       'encounter.encountered_vessel.authorizations.authorized',
       'encounter.encountered_vessel.authorizations.unknown',
       'loitering.total_distance_km', 'loitering.loitering_hours', 'port.lat',
       'port.lon', 'port.country', 'port.name'],
      dtype='object')

In [181]:
loitering.columns = ['id', 'type', 'start', 'end', 'lat', 'lon','mpa', 'eez', 'regions.rfmo','fao', 'major_fao', 'eez12nm',
       'boundingBox', 'startDistanceFromShoreKm', 'endDistanceFromShoreKm',
       'startDistanceFromPortKm', 'endDistanceFromPortKm','vessel.id','vessel.name','vessel.type','vessel.mmsi',
                     'totalTimeHours',
       'totalDistanceKm', 'averageSpeedKnots', 'averageDistanceFromShoreKm']

In [63]:
frames2 = [loitering2,loitering]

result2 = pd.concat(frames2)

In [64]:
result2.shape

(517577, 55)

In [197]:
# compression_opts = dict(method='zip',
#                         archive_name='loitering.csv')  
# result2.to_csv('loitering.zip', index=False,
#           compression=compression_opts)

In [198]:
# loitering[~loitering['id'].isin(loitering2['id'])]

In [199]:
# loitering2['id'].count()

In [201]:
frames3 = [loitering2,loitering[~loitering['id'].isin(loitering2['id'])]]

result3 = pd.concat(frames3)

In [184]:
compression_opts0 = dict(method='zip',
                        archive_name='new_loitering.csv')  
result3.to_csv('new_loitering.zip', index=False,
          compression=compression_opts0)

# Visit merging

In [154]:
def import_data2():
    path = 'gfw_data-v2.xlsx'
    xls = pd.ExcelFile(path)
    dfList = []
    for sheet in ['carrier_port_visit', 'carrier_port_visit-v2']:
        dfList.append(pd.read_excel(path, sheet_name=sheet))
    return dfList

carrier_port_visit, carrier_port_visit2 = import_data2()

In [158]:
carrier_port_visit = carrier_port_visit.drop_duplicates(subset=['event_id'])

In [159]:
carrier_port_visit.columns

Index(['event_id', 'event_type', 'event_start', 'event_end', 'event_lat',
       'event_lon', 'mpa', 'eez', 'rfmo', 'fao', 'major_fao', 'eez12nm',
       'boundingBox', 'startDistanceFromShoreKm', 'endDistanceFromShoreKm',
       'startDistanceFromPortKm', 'endDistanceFromPortKm', 'vessel_id',
       'vessel_flag', 'vessel_name', 'vessel_type', 'vessel_ssvid', 'visitId',
       'confidence', 'durationHrs', 'anchorage_id', 'at_dock',
       'distance_from_shore_km', 'flag', 'id', 'lat', 'lon', 'name',
       'top_destination', 'anchorage_id1', 'at_dock1',
       'distance_from_shore_km1', 'flag1', 'id1', 'lat1', 'lon1', 'name1',
       'top_destination1', 'anchorage_id2', 'at_dock2',
       'distance_from_shore_km2', 'flag2', 'id2', 'lat2', 'lon2', 'name2',
       'top_destination2'],
      dtype='object')

In [168]:
carrier_port_visit2 = carrier_port_visit2[carrier_port_visit2.columns[:11].append(carrier_port_visit2.columns[-4:])]
carrier_port_visit2.columns

Index(['id', 'type', 'start', 'end', 'lat', 'lon', 'vessel.id', 'vessel.type',
       'vessel.mmsi', 'vessel.name', 'vessel.flag', 'port.lat', 'port.lon',
       'port.country', 'port.name'],
      dtype='object')

In [169]:
carrier_port_visit2.columns = ['event_id', 'event_type', 'event_start', 'event_end', 'event_lat',
       'event_lon','vessel_id', 'vessel_type','vessel_ssvid','vessel_name', 'vessel_flag', 'lat','lon','flag','name']

In [175]:
carrier_port_visit2 = carrier_port_visit2[~carrier_port_visit2['event_id'].isin(carrier_port_visit['event_id'])]

In [176]:
framesvisit = [carrier_port_visit,carrier_port_visit2]

resultvisit = pd.concat(framesvisit)

In [177]:
resultvisit

,event_id,event_type,event_start,event_end,event_lat,event_lon,mpa,eez,rfmo,fao,...,top_destination1,anchorage_id2,at_dock2,distance_from_shore_km2,flag2,id2,lat2,lon2,name2,top_destination2
0,f75c1b7d6dc67654840eaa20760cbb76,port_visit,2012-01-01 10:25:07,2012-01-01 11:01:08,60.185100,-1.079800,NaN,5696,"ICCAT, NEAFC, IWC, ACAP, NASCO, NAMMCO, ICES","27, 27.4, 27.4.a",...,PILOT DUTIES LERWICK,489e8ac5,True,1.0,GBR,gbr-lerwick,60.191896,-1.096671,NaN,LERWICK
2,9e9acaba388609d754f0ab3e6dcfc111,port_visit,2012-01-01 17:41:08,2012-01-03 13:16:24,52.159100,3.788000,NaN,5668,"NASCO, NAMMCO, ACAP, ICCAT, IWC, ICES, NEAFC","27.4, 27.4.c, 27",...,ROTTERDAM,47c516d9,False,33.0,NLD,nld-rotterdam,52.178980,3.670723,NaN,ROTTERDAM
4,b467df2426f549e7b9964b22293cbfa1,port_visit,2012-01-02 13:02:47,2012-01-02 17:07:43,52.481700,4.520600,NaN,5668,"NAMMCO, NEAFC, ACAP, ICES, NASCO, ICCAT, IWC","27, 27.4.c, 27.4",...,VELSEN,47c585cf,False,24.0,NLD,nld-amsterdam,52.529468,4.217213,AMSTERDAM,AMSTERDAM
6,69c9c90191ec34a8270a78afde0d0745,port_visit,2012-01-02 13:12:38,2012-01-05 21:20:35,60.140500,-1.136100,NaN,5696,"IWC, ICCAT, NEAFC, NASCO, NAMMCO, ICES, ACAP","27.4, 27.4.a, 27",...,PILOT DUTIES LERWICK,489e8ba3,True,0.0,GBR,gbr-lerwick,60.153944,-1.140599,LERWICK,LERWICK SAR
8,04f1308279e550f4259ef59816f46438,port_visit,2012-01-02 13:12:58,2012-01-04 09:15:38,34.118100,-119.207100,NaN,8456,"IWC, PICES, IATTC, ACAP",77,...,HUENEME,80e84fb5,True,0.0,USA,usa-porthueneme,34.148097,-119.204638,PORT HUENEME,HUENEME
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643484,0e7b14c243a93041c4c06adabd3e8980,port,2014-01-04 09:49:16,2014-01-08 10:50:51,20.755195,-17.061572,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643485,eccf74a3775010a62c7ef191e782a7c9,port,2014-01-04 00:53:46,2014-01-05 05:03:33,51.298117,4.315254,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643486,8c1808a4e82bac8d3f8c0db47d38fee8,port,2014-01-04 19:59:22,2014-01-05 05:12:58,53.978864,-166.412531,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643487,007253fe7ffa79318ff1ab60ccff4fd0,port,2014-01-04 21:10:29,2014-01-05 22:10:48,53.934971,-166.492739,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643488,fcec23ab8f3892b6d258d6c5ca4ca558,port,2014-01-04 13:26:44,2014-01-14 03:38:46,45.287153,14.406227,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [178]:
compression_opts3 = dict(method='zip',
                        archive_name='new_carrier_port_visit.csv')  
resultvisit.to_csv('new_carrier_port_visit_merge.zip', index=False,
          compression=compression_opts3)

In [112]:
carrier_port_visit['event_id'].isin(carrier_port_visit2['id']).sum()

18278

In [113]:
carrier_port_visit2

,id,type,start,end,lat,lon,vessel.id,vessel.type,vessel.mmsi,vessel.name,...,encounter.encountered_vessel.destination_port.country,encounter.encountered_vessel.destination_port.name,encounter.encountered_vessel.authorizations.authorized,encounter.encountered_vessel.authorizations.unknown,loitering.total_distance_km,loitering.loitering_hours,port.lat,port.lon,port.country,port.name
0,af03d0b85979b8c91ae5ea165d0fd2e0,port,2012-10-24 12:21:05 UTC,2012-10-24 21:07:44 UTC,18.460661,-66.111945,3fe8729f8-80c4-2d9b-70cb-02aa09353f4e,carrier,311295000,DOLE ASIA,...,NaN,NaN,NaN,NaN,NaN,NaN,18.460661,-66.111945,PRI,SAN JUAN
1,76c123fc888c38f8424d444308e74739,port,2012-10-24 10:00:48 UTC,2012-10-26 14:49:48 UTC,8.024300,-76.780133,b3089e7df-fd55-d6e8-2292-e7bb093023fe,carrier,308090000,HELLAS STREAM,...,NaN,NaN,NaN,NaN,NaN,NaN,8.024300,-76.780133,COL,TURBO
2,a3910ba2f8e734f7343fe2c3886e031a,port,2012-10-24 23:02:21 UTC,2012-10-25 16:23:59 UTC,62.777300,6.917326,1c3ee5f35-5189-56ac-07a5-a99a6624b7aa,carrier,311411000,SAMSKIP ICE,...,NaN,NaN,NaN,NaN,NaN,NaN,62.777300,6.917326,NOR,NaN
3,c3bf496236204dead751072c35d5fefc,port,2012-10-24 14:57:38 UTC,2012-10-25 16:49:53 UTC,-16.990203,-72.142333,65032eb47-732f-946e-ea32-03567b0cefd8,carrier,636011106,BALTIC PRIDE,...,NaN,NaN,NaN,NaN,NaN,NaN,-16.990203,-72.142333,PER,MATARANI
4,ef23a729101f8d93679a51697754c7c3,port,2012-10-24 07:15:58 UTC,2012-10-25 09:39:17 UTC,52.874624,158.663179,6fc826893-3007-30a2-8cb3-dea6f5087bc0,carrier,273845620,POGRANICHNIK_ZMEEV,...,NaN,NaN,NaN,NaN,NaN,NaN,52.874624,158.663179,RUS,PETROPAVLOVSK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643485,eccf74a3775010a62c7ef191e782a7c9,port,2014-01-04 00:53:46 UTC,2014-01-05 05:03:33 UTC,51.298117,4.315254,f3bef3860-009c-e707-8995-895e9942e745,carrier,566060000,STAR ENDEAVOUR I,...,NaN,NaN,NaN,NaN,NaN,NaN,51.298117,4.315254,BEL,ANTWERP
643486,8c1808a4e82bac8d3f8c0db47d38fee8,port,2014-01-04 19:59:22 UTC,2014-01-05 05:12:58 UTC,53.978864,-166.412531,b59de4765-59b0-b4bf-b763-1ab505626338,carrier,368313000,PACIFIC VENTURE,...,NaN,NaN,NaN,NaN,NaN,NaN,53.978864,-166.412531,USA,DUTCH HARBOR
643487,007253fe7ffa79318ff1ab60ccff4fd0,port,2014-01-04 21:10:29 UTC,2014-01-05 22:10:48 UTC,53.934971,-166.492739,f2b87e8b9-994a-d4f5-43f0-2603490b5e2d,carrier,367151060,KEVLEEN K,...,NaN,NaN,NaN,NaN,NaN,NaN,53.934971,-166.492739,USA,DUTCH HARBOR
643488,fcec23ab8f3892b6d258d6c5ca4ca558,port,2014-01-04 13:26:44 UTC,2014-01-14 03:38:46 UTC,45.287153,14.406227,dd8ce3711-1009-7679-24b1-4582c408ec4c,carrier,314233000,BOSSE,...,NaN,NaN,NaN,NaN,NaN,NaN,45.287153,14.406227,HRV,RIJEKA LUKA
643489,00ee576a6b8b85821f723341e3853b3d,port,2014-01-04 22:43:00 UTC,2014-01-05 11:26:25 UTC,33.682876,130.330082,f65516927-7355-d4be-4ea6-fb95d6013013,carrier,357611000,PACIFIC VIOLET,...,NaN,NaN,NaN,NaN,NaN,NaN,33.682876,130.330082,JPN,FUKUOKA